/**
 * score-impact.ts
 * ───────────────
 * Reads data/posthog-prs.json and writes data/engineer-impact.json.
 *
 * ┌──────────────────────────────────────────────────────────────────────┐
 * │  IMPACT MODEL                                                        │
 * │                                                                      │
 * │  Engineering impact = helping the team ship meaningful product       │
 * │  outcomes, improving reliability/quality, and increasing the         │
 * │  leverage of other engineers.                                        │
 * │                                                                      │
 * │  Dimension             Weight  What we measure                      │
 * │  ─────────────────────────────────────────────                      │
 * │  Product Impact          40%   Feature/product PRs, linked issues,  │
 * │                                core product area coverage            │
 * │  Org Leverage            30%   Reviews given (via reviewed-by),     │
 * │                                PR complexity, cross-author reach     │
 * │  Reliability & Quality   20%   Bugfixes, tests, perf, refactors,    │
 * │                                CI, migrations                        │
 * │  Ownership & Complexity  10%   Cross-stack PRs, schema/infra work,  │
 * │                                multi-area breadth (capped)           │
 * │                                                                      │
 * │  Data coverage notes:                                                │
 * │  • Title/label/linked-issue signals available for 100% of PRs       │
 * │  • File-path signals available for enriched PRs only (~10%)         │
 * │  • Org leverage sourced from reviewed-by queries, not per-PR data   │
 * │                                                                      │
 * │  All sub-scores are summed per engineer, then min-max normalised     │
 * │  (with sqrt compression) across the cohort to 0–100.                │
 * └──────────────────────────────────────────────────────────────────────┘
 *
 * Run: node --env-file=.env.local scripts/score-impact.ts
 */

import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { CollectionResult, PullRequest, FileChange, ReviewedPRSummary } from "./collect-prs.ts";

// Re-export for Dashboard consumption
export type { CollectionResult };

// ─── Output types ──────────────────────────────────────────────────────────

interface DimensionBreakdown {
  score: number;
  rawScore: number;
  formula: string;
  signals: string[];
}

interface RepresentativePR {
  title: string;
  url: string;
  reason: string;
}

type Dimension = "productImpact" | "orgLeverage" | "reliabilityQuality" | "ownershipComplexity";

export interface EngineerImpact {
  rank: number;
  login: string;
  overallScore: number;
  breakdown: Record<Dimension, DimensionBreakdown>;
  strongestDimension: Dimension;
  explanation: string;
  representativePRs: RepresentativePR[];
  confidence: "high" | "medium" | "low";
  confidenceNote: string;
}

export interface ImpactOutput {
  repository: string;
  generatedAt: string;
  windowStart: string;
  windowEnd: string;
  daysAnalyzed: number;
  totalPRsAnalyzed: number;
  totalEngineersFound: number;
  enrichedPRCount: number;
  coverageNote: string;
  weights: Record<Dimension, number>;
  engineers: EngineerImpact[];
}

// ─── Classification helpers ────────────────────────────────────────────────

const CHORE_PREFIX_RE   = /^(chore|revert|bump|release|version)\b/i;
const FEATURE_TITLE_RE  = /\b(feat|feature|add|new|introduce|launch|ship|enable|implement|support|build)\b/i;
const FIX_TITLE_RE      = /\b(fix|bug|regression|hotfix|patch)\b/i;
const REVERT_RE         = /^revert\b/i;
const TEST_TITLE_RE     = /\b(test|spec|coverage|e2e|unit|integration)\b/i;
const PERF_TITLE_RE     = /\b(perf|performance|optim|speed|slow|latency|memory|cache)\b/i;
const REFACTOR_TITLE_RE = /\b(refactor|cleanup|clean.?up|tidy|simplif|reorgani[sz]e)\b/i;
const MIGRATION_TITLE_RE = /\b(migrat|schema|backfill|deprecat|remov|delet)\b/i;
const CI_TITLE_RE       = /\b(ci|cd|workflow|pipeline|action|deploy|release|bump|chore|version)\b/i;
const INFRA_TITLE_RE    = /\b(infra|infrastructure|k8s|kubernetes|docker|helm|terraform)\b/i;

const CORE_PRODUCT_DIRS = new Set([
  "frontend/src", "posthog", "ee", "products", "posthog/api",
  "posthog/hogql", "posthog/hogql_queries", "posthog/models",
  "posthog/temporal", "ee/clickhouse",
]);
const INFRA_DIRS = new Set([".github", "config", "docker", "k8s", "charts"]);

// Only hand-authored test files. __snapshots__ are auto-generated by Jest.
const TEST_FILE_RE      = /\.(test|spec)\.[jt]sx?$|[/\\]__tests__[/\\]/i;
const SNAPSHOT_DIR_RE   = /__snapshots__/i;
const MIGRATION_FILE_RE = /migrations?\//i;
const SCHEMA_FILE_RE    = /schema\.|\.sql$|models\//i;

function topDir(path: string): string {
  const parts = path.split("/");
  return parts.length >= 2 ? `${parts[0]}/${parts[1]}` : parts[0];
}

// File-based predicates — safe to call with null files (return false/null)
function isCoreProduct(files: FileChange[] | null): boolean {
  return files?.some((f) => CORE_PRODUCT_DIRS.has(topDir(f.path))) ?? false;
}
function hasTestFiles(files: FileChange[] | null): boolean {
  return files?.some((f) => TEST_FILE_RE.test(f.path) && !SNAPSHOT_DIR_RE.test(f.path)) ?? false;
}
function hasMigrationFiles(files: FileChange[] | null): boolean {
  return files?.some((f) => MIGRATION_FILE_RE.test(f.path) || SCHEMA_FILE_RE.test(f.path)) ?? false;
}
function hasInfraFiles(files: FileChange[] | null): boolean {
  return files?.some((f) => INFRA_DIRS.has(topDir(f.path))) ?? false;
}
function hasCrossStack(files: FileChange[] | null): boolean {
  if (!files) return false;
  const dirs = new Set(files.map((f) => f.path.split("/")[0]));
  const fe = dirs.has("frontend") || dirs.has("packages");
  const be = dirs.has("posthog") || dirs.has("ee") || dirs.has("products") || dirs.has("services");
  return fe && be;
}

function isBot(login: string): boolean {
  return /\[bot\]$|-bot$|_bot$|dependabot|renovate/i.test(login);
}

function cappedFiles(n: number, cap = 30): number {
  return Math.min(n, cap);
}

// ─── Per-PR classification ──────────────────────────────────────────────────

type PRClass = {
  isFeature: boolean;
  isFix: boolean;
  isTest: boolean;
  isPerf: boolean;
  isRefactor: boolean;
  isMigration: boolean;
  isCI: boolean;
  isInfra: boolean;
  isCoreProduct: boolean;
  hasLinkedIssues: boolean;
  isCrossStack: boolean;
};

function classifyPR(pr: PullRequest): PRClass {
  const t      = pr.title.toLowerCase();
  const labels = pr.labels.map((l) => l.toLowerCase());
  const allText = [t, ...labels].join(" ");
  const isChoreOrRevert = CHORE_PREFIX_RE.test(t);

  return {
    isFeature:    !isChoreOrRevert && (FEATURE_TITLE_RE.test(t) || labels.some((l) => l.startsWith("feat") || l === "enhancement")),
    isFix:        !REVERT_RE.test(t) && (FIX_TITLE_RE.test(t) || labels.some((l) => l === "bug" || l === "fix")),
    isTest:       TEST_TITLE_RE.test(t) || hasTestFiles(pr.files),
    isPerf:       PERF_TITLE_RE.test(allText) || labels.includes("performance"),
    isRefactor:   REFACTOR_TITLE_RE.test(t),
    isMigration:  MIGRATION_TITLE_RE.test(t) || hasMigrationFiles(pr.files),
    isCI:         isChoreOrRevert || (CI_TITLE_RE.test(t) && !FEATURE_TITLE_RE.test(t)),
    isInfra:      INFRA_TITLE_RE.test(t) || hasInfraFiles(pr.files),
    isCoreProduct: isCoreProduct(pr.files),
    hasLinkedIssues: pr.linkedIssues.length > 0,
    isCrossStack: hasCrossStack(pr.files),
  };
}

// ─── Accumulator ───────────────────────────────────────────────────────────

interface EngAcc {
  productRaw: number;
  orgRaw: number;
  qualityRaw: number;
  ownershipRaw: number;

  mergedPRs: PullRequest[];
  featurePRs: PullRequest[];
  fixPRs: PullRequest[];
  testPRs: PullRequest[];
  reviewedPRs: { pr: PullRequest; substantive: boolean }[];
  reviewedAuthors: Set<string>;
  crossStackPRs: PullRequest[];
  migrationPRs: PullRequest[];
  linkedIssuePRs: PullRequest[];
  topDirs: Map<string, number>;
}

function newAcc(): EngAcc {
  return {
    productRaw: 0, orgRaw: 0, qualityRaw: 0, ownershipRaw: 0,
    mergedPRs: [], featurePRs: [], fixPRs: [], testPRs: [],
    reviewedPRs: [], reviewedAuthors: new Set(),
    crossStackPRs: [], migrationPRs: [], linkedIssuePRs: [],
    topDirs: new Map(),
  };
}

// ─── Main ───────────────────────────────────────────────────────────────────

async function main() {
  const ROOT = process.cwd();
  const collection: CollectionResult = JSON.parse(
    await readFile(join(ROOT, "data", "posthog-prs.json"), "utf8"),
  );

  const allPRs = collection.pullRequests.filter(
    (pr) => pr.author && !isBot(pr.author),
  );

  const windowStart   = new Date(collection.windowStart);
  const windowEnd     = new Date(collection.windowEnd);
  const daysCollected = Math.floor((windowEnd.getTime() - windowStart.getTime()) / 86_400_000);

  // ── Build per-engineer accumulators ──────────────────────────────────────
  const accs = new Map<string, EngAcc>();
  const getAcc = (login: string) => {
    if (!accs.has(login)) accs.set(login, newAcc());
    return accs.get(login)!;
  };

  const prByNum = new Map(allPRs.map((pr) => [pr.number, pr]));

  for (const pr of allPRs) {
    const author = pr.author!;
    const cls    = classifyPR(pr);
    const acc    = getAcc(author);
    acc.mergedPRs.push(pr);

    // Track top directories (enriched PRs only)
    if (pr.files) {
      for (const f of pr.files) {
        const d = topDir(f.path);
        if (!SNAPSHOT_DIR_RE.test(d)) {
          acc.topDirs.set(d, (acc.topDirs.get(d) ?? 0) + 1);
        }
      }
    }

    // ── Product Impact ────────────────────────────────────────────────────
    if (!cls.isCI || cls.isFeature) {
      let p = 0;
      if (cls.isFeature)       p += 3.0;
      if (cls.hasLinkedIssues) p += 2.0;
      if (cls.isCoreProduct)   p += 1.0;
      if (!cls.isFeature && !cls.isFix && !cls.isCI) p += 0.5;
      acc.productRaw += p;
      if (cls.isFeature)       acc.featurePRs.push(pr);
      if (cls.hasLinkedIssues) acc.linkedIssuePRs.push(pr);
    }

    // ── Reliability & Quality ─────────────────────────────────────────────
    if (cls.isFix)      { acc.qualityRaw += 2.0; acc.fixPRs.push(pr); }
    if (cls.isTest)     { acc.qualityRaw += 1.5; acc.testPRs.push(pr); }
    if (cls.isPerf)       acc.qualityRaw += 1.5;
    if (cls.isRefactor)   acc.qualityRaw += 1.0;
    if (cls.isMigration) { acc.qualityRaw += 1.0; acc.migrationPRs.push(pr); }
    if (cls.isCI)         acc.qualityRaw += 0.5;

    // ── Ownership & Complexity ────────────────────────────────────────────
    let o = 0;
    if (cls.isCrossStack)  { o += 2.0; acc.crossStackPRs.push(pr); }
    if (cls.isMigration || hasMigrationFiles(pr.files)) o += 1.5;
    if (cls.isInfra)         o += 1.0;
    o += cappedFiles(pr.changedFiles, 30) / 30; // 0–1, capped
    acc.ownershipRaw += o;
  }

  // ── Org Leverage — sourced from reviewed-by queries ─────────────────────
  // Each entry in reviewedByEngineer[login] is a PR they formally reviewed.
  // All entries are substantive (GitHub's reviewed-by: only includes formal reviews).
  for (const [reviewerLogin, reviewedPRs] of Object.entries(collection.reviewedByEngineer ?? {})) {
    if (isBot(reviewerLogin)) continue;
    const acc = getAcc(reviewerLogin);
    for (const rv of reviewedPRs) {
      if (isBot(rv.prAuthor)) continue;
      // Use changedFiles (if known) to weight complex PRs higher; 15 = median default
      const cf = rv.changedFiles > 0 ? rv.changedFiles : 15;
      const complexityWeight = 0.5 + (cappedFiles(cf, 40) / 40) * 0.5; // 0.5–1.0
      acc.orgRaw += 2.0 * complexityWeight;
      acc.reviewedAuthors.add(rv.prAuthor);
      const pr = prByNum.get(rv.prNumber);
      if (pr) acc.reviewedPRs.push({ pr, substantive: true });
    }
  }

  // Cross-author reach bonus
  for (const [, acc] of accs) {
    acc.orgRaw += Math.log2(acc.reviewedAuthors.size + 1) * 2;
  }

  // ── Normalise to 0–100 with sqrt compression ──────────────────────────
  const logins = [...accs.keys()];
  const rawVals = (dim: keyof Pick<EngAcc, "productRaw" | "orgRaw" | "qualityRaw" | "ownershipRaw">) =>
    logins.map((l) => accs.get(l)![dim]);

  function normalise(values: number[]): number[] {
    const compressed = values.map((v) => Math.sqrt(Math.max(v, 0)));
    const min = Math.min(...compressed);
    const max = Math.max(...compressed);
    if (max === min) return values.map(() => 50);
    return compressed.map((v) => Math.round(((v - min) / (max - min)) * 100));
  }

  const normProduct   = normalise(rawVals("productRaw"));
  const normOrg       = normalise(rawVals("orgRaw"));
  const normQuality   = normalise(rawVals("qualityRaw"));
  const normOwnership = normalise(rawVals("ownershipRaw"));

  const WEIGHTS: Record<Dimension, number> = {
    productImpact:       0.40,
    orgLeverage:         0.30,
    reliabilityQuality:  0.20,
    ownershipComplexity: 0.10,
  };

  // ── Representative PR selection ─────────────────────────────────────────

  const TRIVIAL_RE = /__snapshots__|\.snap$|package-lock\.json|yarn\.lock|pnpm-lock|\.gitignore|\.prettier|\.eslint|\.editorconfig|node_modules|_tmp_|^package\.json$|\.semgrep/i;
  const DIR_PRIORITY: Record<string, number> = {
    "posthog": 10, "ee": 10, "rust": 9, "products": 9,
    "services": 8, "frontend/src": 8, "packages": 7,
    ".github": 5, "bin": 4,
  };

  function meaningfulDir(pr: PullRequest): string {
    if (pr.files && pr.files.length > 0) {
      const scored = pr.files
        .filter((f) => !TRIVIAL_RE.test(f.path))
        .map((f) => {
          const dir = topDir(f.path);
          const priority = DIR_PRIORITY[dir] ?? DIR_PRIORITY[f.path.split("/")[0]] ?? 3;
          return { f, priority };
        })
        .sort((a, b) => b.priority - a.priority);
      const best = scored[0]?.f ?? pr.files[0];
      return topDir(best?.path ?? "codebase");
    }
    // Fallback: infer from title
    const t = pr.title.toLowerCase();
    if (t.includes("frontend") || t.includes(" ui ") || t.includes("component")) return "frontend";
    if (t.includes("api") || t.includes("backend") || t.includes("server")) return "backend";
    if (t.includes("hogql") || t.includes("clickhouse")) return "posthog/hogql";
    return "codebase";
  }

  // ── Build output ──────────────────────────────────────────────────────────

  const results: EngineerImpact[] = logins.map((login, i) => {
    const acc = accs.get(login)!;

    const dimScores: Record<Dimension, number> = {
      productImpact:       normProduct[i],
      orgLeverage:         normOrg[i],
      reliabilityQuality:  normQuality[i],
      ownershipComplexity: normOwnership[i],
    };

    const overallScore = Math.round(
      dimScores.productImpact       * WEIGHTS.productImpact +
      dimScores.orgLeverage         * WEIGHTS.orgLeverage +
      dimScores.reliabilityQuality  * WEIGHTS.reliabilityQuality +
      dimScores.ownershipComplexity * WEIGHTS.ownershipComplexity,
    );

    const strongestDimension = (Object.keys(dimScores) as Dimension[]).reduce(
      (best, d) => (dimScores[d] > dimScores[best] ? d : best),
    );

    const topAreas = [...acc.topDirs.entries()]
      .sort((a, b) => b[1] - a[1])
      .slice(0, 3)
      .map(([d]) => d);

    // Evidence bullets
    const featCount     = acc.featurePRs.length;
    const fixCount      = acc.fixPRs.length;
    const issuePRCount  = acc.linkedIssuePRs.length;
    const substReviews  = acc.reviewedPRs.filter((r) => r.substantive).length;
    const reachCount    = acc.reviewedAuthors.size;

    const evidence: string[] = [];
    if (featCount > 0)       evidence.push(`${featCount} feature/product PR${featCount !== 1 ? "s" : ""} merged`);
    if (issuePRCount > 0)    evidence.push(`${issuePRCount} PR${issuePRCount !== 1 ? "s" : ""} closed tracked GitHub issues`);
    if (fixCount > 0)        evidence.push(`${fixCount} bug fix${fixCount !== 1 ? "es" : ""} merged`);
    if (acc.testPRs.length > 0) evidence.push(`${acc.testPRs.length} PR${acc.testPRs.length !== 1 ? "s" : ""} added or improved tests`);
    if (substReviews > 0)    evidence.push(`${substReviews} substantive review${substReviews !== 1 ? "s" : ""} for ${reachCount} colleague${reachCount !== 1 ? "s" : ""}`);
    if (acc.crossStackPRs.length > 0) evidence.push(`${acc.crossStackPRs.length} cross-stack PR${acc.crossStackPRs.length !== 1 ? "s" : ""} (frontend + backend)`);
    if (acc.migrationPRs.length > 0)  evidence.push(`${acc.migrationPRs.length} schema/migration PR${acc.migrationPRs.length !== 1 ? "s" : ""}`);
    if (topAreas.length > 0) evidence.push(`Primary areas: ${topAreas.join(", ")}`);

    // Narrative
    const areaPhrase = topAreas.slice(0, 2).join(" and ") || "the codebase";
    let rolePhrase: string;
    if (strongestDimension === "orgLeverage") {
      rolePhrase = `Broadest review reach — reviewed ${substReviews} PRs for ${reachCount} colleagues`;
    } else if (strongestDimension === "ownershipComplexity") {
      rolePhrase = `Cross-stack engineer spanning ${areaPhrase}`;
    } else if (strongestDimension === "reliabilityQuality") {
      rolePhrase = `Quality-focused contributor in ${areaPhrase}`;
    } else {
      rolePhrase = `Product contributor in ${areaPhrase}`;
    }

    const deliveryParts: string[] = [];
    if (featCount > 0)      deliveryParts.push(`${featCount} feature${featCount !== 1 ? "s" : ""} shipped`);
    if (issuePRCount > 0)   deliveryParts.push(`${issuePRCount} tracked issue${issuePRCount !== 1 ? "s" : ""} resolved`);
    if (acc.crossStackPRs.length > 0 && strongestDimension !== "ownershipComplexity")
      deliveryParts.push(`${acc.crossStackPRs.length} cross-stack PR${acc.crossStackPRs.length !== 1 ? "s" : ""}`);
    if (acc.migrationPRs.length > 0)
      deliveryParts.push(`${acc.migrationPRs.length} schema migration${acc.migrationPRs.length !== 1 ? "s" : ""}`);

    const collabParts: string[] = [];
    if (substReviews > 0 && strongestDimension !== "orgLeverage")
      collabParts.push(`reviewed ${substReviews} PR${substReviews !== 1 ? "s" : ""} for ${reachCount} colleague${reachCount !== 1 ? "s" : ""}`);
    if (fixCount > 0 && strongestDimension === "reliabilityQuality")
      collabParts.push(`${fixCount} bug fix${fixCount !== 1 ? "es" : ""}`);

    let explanation = rolePhrase;
    if (deliveryParts.length > 0) explanation += ` — ${deliveryParts.join(", ")}`;
    if (collabParts.length > 0)   explanation += `; ${collabParts.join(", ")}`;
    explanation += ".";

    // Representative PRs
    const candidatePRs: RepresentativePR[] = [];
    const pickBest = (pool: PullRequest[], reason: (pr: PullRequest) => string) => {
      const sorted = [...pool]
        .sort((a, b) =>
          (b.linkedIssues.length - a.linkedIssues.length) || (b.changedFiles - a.changedFiles),
        )
        .slice(0, 2);
      for (const pr of sorted) {
        if (candidatePRs.length < 3 && !candidatePRs.some((c) => c.url === pr.url)) {
          candidatePRs.push({ title: pr.title, url: pr.url, reason: reason(pr) });
        }
      }
    };

    pickBest(acc.featurePRs,    (pr) => `Feature PR${pr.linkedIssues.length > 0 ? ` closing issue #${pr.linkedIssues[0].number}` : ""} in ${meaningfulDir(pr)}`);
    pickBest(acc.fixPRs,        (pr) => `Bug fix in ${meaningfulDir(pr)}`);
    pickBest(acc.crossStackPRs, (pr) => `Cross-stack change (frontend + backend, ${pr.changedFiles} files)`);
    pickBest(acc.migrationPRs,  (pr) => `Schema/migration change in ${meaningfulDir(pr)}`);
    pickBest(acc.mergedPRs.filter((p) => p.linkedIssues.length > 0), (pr) => `Closed tracked issue #${pr.linkedIssues[0].number}`);
    pickBest(acc.mergedPRs.filter((p) => !classifyPR(p).isCI), (pr) => `Merged into ${meaningfulDir(pr)}`);

    // Confidence
    const isActive = acc.mergedPRs.length >= 3;
    const confidence: EngineerImpact["confidence"] =
      daysCollected >= 80 ? (isActive ? "high" : "medium")
      : daysCollected >= 40 ? (isActive ? "medium" : "low")
      : "low";

    const confidenceNote = daysCollected >= 80
      ? `Based on ${daysCollected} days of data.`
      : `Based on ${daysCollected} of 90 days — scores may shift with a complete window.`;

    return {
      rank: 0,
      login,
      overallScore,
      breakdown: {
        productImpact: {
          score: dimScores.productImpact, rawScore: acc.productRaw,
          formula: "Feature PRs × 3 + linked-issue PRs × 2 + core-product PRs × 1. Title/label signals for all PRs; file-area signals for enriched PRs.",
          signals: evidence.filter((e) => e.includes("feature") || e.includes("issue") || e.includes("Primary")),
        },
        orgLeverage: {
          score: dimScores.orgLeverage, rawScore: acc.orgRaw,
          formula: "Formal reviews × 2 × complexity weight (0.5–1.0 by PR size) + log₂(distinct colleagues + 1) × 2. Sourced from reviewed-by: queries, covering all active engineers.",
          signals: evidence.filter((e) => e.includes("review") || e.includes("colleague")),
        },
        reliabilityQuality: {
          score: dimScores.reliabilityQuality, rawScore: acc.qualityRaw,
          formula: "Bug fixes × 2 + tests × 1.5 + perf × 1.5 + refactors × 1 + migrations × 1 + CI × 0.5. A PR can score multiple categories.",
          signals: evidence.filter((e) => e.includes("bug") || e.includes("test") || e.includes("schema") || e.includes("migration")),
        },
        ownershipComplexity: {
          score: dimScores.ownershipComplexity, rawScore: acc.ownershipRaw,
          formula: "Cross-stack PRs × 2 + migration/schema × 1.5 + infra × 1 + file-breadth (0–1, capped at 30). Cross-stack detection requires file enrichment.",
          signals: evidence.filter((e) => e.includes("cross-stack") || e.includes("schema") || e.includes("migration")),
        },
      },
      strongestDimension,
      explanation,
      representativePRs: candidatePRs.slice(0, 3),
      confidence,
      confidenceNote,
    };
  });

  results.sort((a, b) => b.overallScore - a.overallScore);
  results.forEach((e, i) => (e.rank = i + 1));
  const top10 = results.slice(0, 10);

  const output: ImpactOutput = {
    repository:      collection.repository,
    generatedAt:     collection.generatedAt,
    windowStart:     collection.windowStart,
    windowEnd:       collection.windowEnd,
    daysAnalyzed:    daysCollected,
    totalPRsAnalyzed: allPRs.length,
    totalEngineersFound: results.length,
    enrichedPRCount: collection.enrichedPRCount ?? 0,
    coverageNote:    collection.coverageNote ?? "",
    weights:         WEIGHTS,
    engineers:       top10,
  };

  await writeFile(join(ROOT, "data", "engineer-impact.json"), JSON.stringify(output, null, 2));

  console.log(`\n${"─".repeat(72)}`);
  console.log(`${collection.repository} · ${daysCollected} days · ${allPRs.length} PRs · ${results.length} engineers`);
  console.log(`${"─".repeat(72)}`);
  for (const e of top10.slice(0, 5)) {
    const d = e.breakdown;
    console.log(
      `#${String(e.rank).padEnd(2)} ${e.login.padEnd(24)} overall=${e.overallScore}` +
      `  prod=${d.productImpact.score}  org=${d.orgLeverage.score}  qual=${d.reliabilityQuality.score}  own=${d.ownershipComplexity.score}`,
    );
    console.log(`    ${e.explanation}`);
  }
  console.log(`\nTop-10 written to data/engineer-impact.json`);
}

main().catch((err) => { console.error(err); process.exit(1); });
